apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: pages
  name: pages
  namespace: beta
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: pages
  strategy: {}
  template: 
    metadata: 
      labels: 
        app: pages
    spec: 
      containers: 
        - 
          env: 
            - 
              name: PAGE_CONTENT
              valueFrom: 
                configMapKeyRef: 
                  key: PAGE_CONTENT
                  name: pages-config-map
          image: "loki212/pages:pipeline"
          name: pages
          ports: 
            - 
              containerPort: 8080

